Remove some unrefenced primitives and update primitive table
pharo-project/pharo-vm pull request #134
Opened 2020-11-27 11:15 UTC by Alisu

As title says, see if CI pass.

2020-11-30 17:23 UTC, guillep requested changes

2020-11-30 17:23 UTC, guillep commented on smalltalksrc/VMMaker/InterpreterPrimitives.class.st
> -InterpreterPrimitives >> primitiveEnterCriticalSection [
These we should keep, and we should use in the image to have a proper mutex implementation

2020-11-30 17:23 UTC, guillep commented on smalltalksrc/VMMaker/InterpreterPrimitives.class.st
> -	"Exit the critical section.
Same

2020-11-30 17:23 UTC, guillep commented on smalltalksrc/VMMaker/CoInterpreterPrimitives.class.st
> -CoInterpreterPrimitives >> primitiveContextXray [
I wouldn't remove this one yet, it could be useful in the future...

2020-11-30 17:23 UTC, guillep commented on smalltalksrc/VMMaker/StackInterpreterMT.class.st
> -StackInterpreterMT >> primitiveEnterCriticalSection [
Same

2020-11-30 17:23 UTC, guillep commented on smalltalksrc/VMMaker/StackInterpreterMT.class.st
> -StackInterpreterMT >> primitiveExitCriticalSection [
Same

2020-11-30 17:23 UTC, guillep commented on smalltalksrc/VMMaker/StackInterpreterPrimitives.class.st
> -StackInterpreterPrimitives >> primitiveContextXray [
Same

2020-11-30 18:05 UTC, Alisu commented
Btw i did not understand your message but i have a mutex implementation for the channel, i can push it if needed.

2021-03-10 14:29 UTC, guillep requested changes

2021-03-10 14:29 UTC, guillep commented on smalltalksrc/VMMaker/StackInterpreter.class.st
> +		(182 primitiveFail)			"primitiveSizeInBytes"
We should undo this line

2021-03-10 14:29 UTC, guillep commented on smalltalksrc/VMMaker/StackInterpreter.class.st
> +		(187 primitiveFail) "primitiveTestAndSetOwnershipOfCriticalSection""was primitiveClosureValueWithArgs"
We should undo these 3 lines

2021-03-10 14:29 UTC, guillep commented on smalltalksrc/VMMaker/StackInterpreter.class.st
> +		(213 primitiveFail)			"primitiveContextXray"
We should undo this line

2021-03-10 14:39 UTC, guillep approved these changes

2021-03-10 14:39 UTC, merged