Generate Pharo VM dependency graph
pharo-project/pharo-vm pull request #554
Opened 2023-03-15 17:00 UTC by hernanmd

This PR makes cmake to generate a GraphViz PNG with the VM dependency graph, in the build directory.
Add the option BUILD_WITH_GRAPHVIZ (default set to TRUE) in CMakeLists.txt
Handle the case of dot not present in the target system (find_program(DOT dot)...)

2023-03-16 08:05 UTC, guillep requested changes

2023-03-16 08:05 UTC, guillep commented on CMakeLists.txt
> +find_program(DOT dot)
Good! I'd add a comment explaining what this is doing and why, what do you think?

2023-03-16 08:05 UTC, guillep commented on CMakeLists.txt
> +            COMMAND cp ${CMAKE_SOURCE_DIR}/cmake/CMakeGraphVizOptions.cmake .
1) This line is especially tricky :) It's important to know that the `CMakeGraphVizOptions.cmake` file is searched for in the binary dir. https://cmake.org/cmake/help/latest/module/CMakeGraphVizOptions.html
Maybe we can add a link to the doc?

2023-03-16 08:05 UTC, guillep commented on cmake/CMakeGraphVizOptions.cmake
> +set(GRAPHVIZ_GRAPH_NAME "Pharo VM Dependencies")
Maybe we do not want spaces here? Because this is going to be used above as file name! And spaces in file names are always a source of trouble...

2023-03-17 15:24 UTC, hernanmd commented on cmake/CMakeGraphVizOptions.cmake
> +set(GRAPHVIZ_GRAPH_NAME "Pharo VM Dependencies")
Ok, removed spaces.

2023-03-17 15:25 UTC, hernanmd reviewed
Reviewed and applied requested changes.

2023-03-20 13:32 UTC, guillep approved these changes
Cool! I'll remove a line over there and merge!

2023-03-20 13:32 UTC, guillep commented on CMakeLists.txt
> +    include(cmake/CMakeGraphVizOptions.cmake)
```suggestion
```

2023-03-20 13:32 UTC, merged

2023-03-20 13:33 UTC, guillep commented
Thanks!